### ISSUE TITLE
Tests tracking issue

### ISSUE THREAD

**Issue by kosiokarchev** [kosiokarchev/phytorch#6]
Concrete tests:

- [ ] quantities
   - `(value * unit) / unit` vs `unit / unit`
- [ ] roots
  - gradient
- [ ] ellipr
- [ ] ellip
- [ ] `gammaincc?(inv)?`: tests from `scipy`, `mpmath`

Framework improvements:

- [ ] set up CI
- [ ] set up coverage reporting
